//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoAPKTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoAPKTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APK|*.apk|All|*.*.
        /// </summary>
        internal static string apk_files {
            get {
                return ResourceManager.GetString("apk_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未发现自定义jks。是否选择jks？.
        /// </summary>
        internal static string ask_custom_jks {
            get {
                return ResourceManager.GetString("ask_custom_jks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 发现自定义jks。选择“是”：校验；“否”：重新选择jks；&quot;取消“：终止操作.
        /// </summary>
        internal static string ask_found_custom_jks {
            get {
                return ResourceManager.GetString("ask_found_custom_jks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是否保存为自定义签名？.
        /// </summary>
        internal static string ask_save_custom_jks {
            get {
                return ResourceManager.GetString("ask_save_custom_jks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在回编译dex....
        /// </summary>
        internal static string compiling_dex {
            get {
                return ResourceManager.GetString("compiling_dex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 执行完成.
        /// </summary>
        internal static string complete {
            get {
                return ResourceManager.GetString("complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 转换出现异常.
        /// </summary>
        internal static string convert_expcetion {
            get {
                return ResourceManager.GetString("convert_expcetion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自定义签名校验无误，无需保存.
        /// </summary>
        internal static string custom_jks_correct {
            get {
                return ResourceManager.GetString("custom_jks_correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在反编译....
        /// </summary>
        internal static string decompiling {
            get {
                return ResourceManager.GetString("decompiling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在反编译dex....
        /// </summary>
        internal static string decompiling_dex {
            get {
                return ResourceManager.GetString("decompiling_dex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEX|*.dex|All|*.*.
        /// </summary>
        internal static string dex_files {
            get {
                return ResourceManager.GetString("dex_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在dex2jar.
        /// </summary>
        internal static string dex2jar_ing {
            get {
                return ResourceManager.GetString("dex2jar_ing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///.
        /// </summary>
        internal static string enter {
            get {
                return ResourceManager.GetString("enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 失败！.
        /// </summary>
        internal static string failed {
            get {
                return ResourceManager.GetString("failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件夹|*.
        /// </summary>
        internal static string files {
            get {
                return ResourceManager.GetString("files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 完成！.
        /// </summary>
        internal static string finish {
            get {
                return ResourceManager.GetString("finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示.
        /// </summary>
        internal static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示.
        /// </summary>
        internal static string info_ {
            get {
                return ResourceManager.GetString("info_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 配置文件不存在.
        /// </summary>
        internal static string ini_settings_file_not_found {
            get {
                return ResourceManager.GetString("ini_settings_file_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jar|*.jar.
        /// </summary>
        internal static string jar_files {
            get {
                return ResourceManager.GetString("jar_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在jar2dex....
        /// </summary>
        internal static string jar2dex_ing {
            get {
                return ResourceManager.GetString("jar2dex_ing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 运行....
        /// </summary>
        internal static string launching {
            get {
                return ResourceManager.GetString("launching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 生成成功.
        /// </summary>
        internal static string make_succ {
            get {
                return ResourceManager.GetString("make_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 需要批量反编译吗.
        /// </summary>
        internal static string need_decompiles {
            get {
                return ResourceManager.GetString("need_decompiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 需要批量签名吗.
        /// </summary>
        internal static string need_signs {
            get {
                return ResourceManager.GetString("need_signs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未发现apk文件!.
        /// </summary>
        internal static string no_find_apk {
            get {
                return ResourceManager.GetString("no_find_apk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未发现dex文件!.
        /// </summary>
        internal static string no_find_dex {
            get {
                return ResourceManager.GetString("no_find_dex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未发现framework框架，请自行将odex所在的手机或模拟器上system下的framework文件夹放在工具箱的tool文件夹下内，请勿重命名!.
        /// </summary>
        internal static string no_find_framework {
            get {
                return ResourceManager.GetString("no_find_framework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未发现jar文件!.
        /// </summary>
        internal static string no_find_jar {
            get {
                return ResourceManager.GetString("no_find_jar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未发现odex文件!.
        /// </summary>
        internal static string no_find_odex {
            get {
                return ResourceManager.GetString("no_find_odex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未发现smali文件夹!.
        /// </summary>
        internal static string no_find_smali_files {
            get {
                return ResourceManager.GetString("no_find_smali_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未发现签名文件!.
        /// </summary>
        internal static string no_sign {
            get {
                return ResourceManager.GetString("no_sign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string odex_ing {
            get {
                return ResourceManager.GetString("odex_ing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开.
        /// </summary>
        internal static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在打开....
        /// </summary>
        internal static string opening {
            get {
                return ResourceManager.GetString("opening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在打包....
        /// </summary>
        internal static string packaging {
            get {
                return ResourceManager.GetString("packaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 路径: {0}.
        /// </summary>
        internal static string path {
            get {
                return ResourceManager.GetString("path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请正确配置.
        /// </summary>
        internal static string pls_config {
            get {
                return ResourceManager.GetString("pls_config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请确认是否已经拖入反编译后的文件夹!.
        /// </summary>
        internal static string pls_confirm_decompile_package {
            get {
                return ResourceManager.GetString("pls_confirm_decompile_package", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请输入指令哦.
        /// </summary>
        internal static string pls_input_opcode {
            get {
                return ResourceManager.GetString("pls_input_opcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请检测根目录下是否包含as.exe程序.
        /// </summary>
        internal static string pls_insure_your_as_path {
            get {
                return ResourceManager.GetString("pls_insure_your_as_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请确认指令是否正确.
        /// </summary>
        internal static string pls_make_sure {
            get {
                return ResourceManager.GetString("pls_make_sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存成功.
        /// </summary>
        internal static string save_succeed {
            get {
                return ResourceManager.GetString("save_succeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在签名....
        /// </summary>
        internal static string signing {
            get {
                return ResourceManager.GetString("signing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成功！.
        /// </summary>
        internal static string succeed {
            get {
                return ResourceManager.GetString("succeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支持类型|*.apk;*.jar;*.odex;*.dex.
        /// </summary>
        internal static string support_file {
            get {
                return ResourceManager.GetString("support_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 支持类型|*.jks.
        /// </summary>
        internal static string support_jks {
            get {
                return ResourceManager.GetString("support_jks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在努力执行中....
        /// </summary>
        internal static string working_hard {
            get {
                return ResourceManager.GetString("working_hard", resourceCulture);
            }
        }
    }
}
